# TO IMPLEMENT FIND S ALGORITHM

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/enjoysport.csv')

In [ ]:
df

     sky airtemp humidity    wind water forcast enjoysport
0  sunny    warm   normal  strong  warm    same        yes
1  sunny    warm     high  strong  warm    same        yes
2  rainy    cold     high  strong  warm  change         no
3  sunny    warm     high  strong  cool  change        yes

Baisc eda

In [ ]:
df.tail()

     sky airtemp humidity    wind water forcast enjoysport
0  sunny    warm   normal  strong  warm    same        yes
1  sunny    warm     high  strong  warm    same        yes
2  rainy    cold     high  strong  warm  change         no
3  sunny    warm     high  strong  cool  change        yes

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sky         4 non-null      object
 1   airtemp     4 non-null      object
 2   humidity    4 non-null      object
 3   wind        4 non-null      object
 4   water       4 non-null      object
 5   forcast     4 non-null      object
 6   enjoysport  4 non-null      object
dtypes: object(7)
memory usage: 356.0+ bytes

In [ ]:
df.isnull()

     sky  airtemp  humidity   wind  water  forcast  enjoysport
0  False    False     False  False  False    False       False
1  False    False     False  False  False    False       False
2  False    False     False  False  False    False       False
3  False    False     False  False  False    False       False

In [ ]:
concepts=np.array(df.iloc[:,:-1])
target=np.array(df.iloc[:,-1])

In [ ]:
concepts

array([['sunny', 'warm', 'normal', 'strong', 'warm', 'same'],
       ['sunny', 'warm', 'high', 'strong', 'warm', 'same'],
       ['rainy', 'cold', 'high', 'strong', 'warm', 'change'],
       ['sunny', 'warm', 'high', 'strong', 'cool', 'change']],
      dtype=object)

In [ ]:
target

array(['yes', 'yes', 'no', 'yes'], dtype=object)

In [ ]:
def train(con,tar):
  for i,val in enumerate(tar):
    if val=='yes':
      specific_h=con[i].copy()
      break
  for i,val in enumerate(con):
    if tar[i]=='yes':
      for x in range(len(specific_h)):
        if val[x]!=specific_h[x]:
          specific_h[x]='?'
        else:
          pass
      print(specific_h)

  return specific_h

In [ ]:
train(concepts,target)

['sunny' 'warm' 'normal' 'strong' 'warm' 'same']
['sunny' 'warm' '?' 'strong' 'warm' 'same']
['sunny' 'warm' '?' 'strong' '?' '?']

array(['sunny', 'warm', '?', 'strong', '?', '?'], dtype=object)